import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type PortfolioDocument = Portfolio & Document;

@Schema({ timestamps: true })
export class Asset {
  // _id is auto-generated by Mongoose for subdocuments
  _id: Types.ObjectId;

  @Prop({ required: true })
  name: string;

  @Prop({ required: true })
  symbol: string;

  @Prop({ required: true, enum: ['STOCK', 'BOND', 'MUTUAL_FUND', 'CRYPTO', 'CASH'] })
  type: string;

  @Prop({ required: true, min: 0 })
  quantity: number;

  @Prop({ required: true, min: 0 })
  purchasePrice: number;

  @Prop({ required: true, min: 0 })
  currentPrice: number;
}

const AssetSchema = SchemaFactory.createForClass(Asset);

@Schema({ timestamps: true })
export class Portfolio {
  @Prop({ type: Types.ObjectId, ref: 'User', required: true, unique: true })
  userId: Types.ObjectId;

  @Prop({ type: [AssetSchema], default: [] })
  assets: Asset[];
}

export const PortfolioSchema = SchemaFactory.createForClass(Portfolio);
